# Generated by Django 5.1.4 on 2024-12-11 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('customer_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('customer_occupation', models.CharField(max_length=50)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_transaction_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('merchant_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transaction_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Transaction_Date', models.DateTimeField()),
                ('Transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('transaction_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('login_attempt', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Channel', models.CharField(max_length=50)),
                ('Account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions_app.accounts')),
                ('Device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions_app.devices')),
                ('Merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions_app.merchants')),
            ],
        ),
    ]
