# Generated by Django 5.1.4 on 2024-12-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='account_balance',
            new_name='AccountBalance',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='account_id',
            new_name='AccountID',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='customer_age',
            new_name='CustomerAge',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='customer_occupation',
            new_name='CustomerOccupation',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='previous_transaction_date',
            new_name='PreviousTransactionDate',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='device_id',
            new_name='DeviceID',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='ip_address',
            new_name='IPAddress',
        ),
        migrations.RenameField(
            model_name='merchants',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='merchants',
            old_name='merchant_id',
            new_name='MerchantID',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Account_id',
            new_name='AccountID',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Device_id',
            new_name='DeviceID',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='login_attempt',
            new_name='LoginAttempts',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Merchant_id',
            new_name='MerchantID',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Transaction_amount',
            new_name='TransactionAmount',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Transaction_Date',
            new_name='TransactionDate',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_duration',
            new_name='TransactionDuration',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Transaction_id',
            new_name='TransactionID',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Transaction_type',
            new_name='TransactionType',
        ),
    ]
