# Generated by Django 5.1.4 on 2024-12-20 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0005_alter_transactions_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='AccountBalance',
            field=models.DecimalField(decimal_places=2, default=0, error_messages={'invalid': 'Invalid Account Balance, must be a non-negative number'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Channel',
            field=models.CharField(choices=[('ATM', 'ATM'), ('Online', 'Online'), ('Branch', 'Branch')], error_messages={'invalid': 'Invalid Channel, must be ATM, Online, or Branch'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='CustomerAge',
            field=models.IntegerField(default=15, error_messages={'invalid': 'Invalid Customer Age, must be a non-negative number'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='LoginAttempts',
            field=models.IntegerField(error_messages={'invalid': 'Invalid Login Attempts, must be a non-negative number'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='TransactionAmount',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Invalid Transaction Amount, must be a non-negative number'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='TransactionDuration',
            field=models.IntegerField(error_messages={'invalid': 'Invalid Transaction Duration, must be a non-negative number'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='TransactionType',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], error_messages={'invalid': 'Invalid Transaction Type, must be Credit or Debit'}, max_length=10),
        ),
    ]
